In [7]:
import pandas as pd
import numpy as np

df = pd.read_csv("/Users/rebeccasonn-lees/Downloads/PDI/pdi_pensions/data/csv/morg08.csv")
df.head()
df.columns

Index(['hhid', 'intmonth', 'hurespli', 'hrhtype', 'minsamp', 'hrlonglk',
       'hrsample', 'hrhhid2', 'serial', 'hhnum', 'state', 'stfips', 'cbsafips',
       'county', 'centcity', 'smsastat', 'icntcity', 'smsa04', 'relref95',
       'age', 'spouse', 'sex', 'grade92', 'race', 'ethnic', 'lineno', 'famnum',
       'pfamrel', 'marital', 'prpertyp', 'penatvty', 'pemntvty', 'pefntvty',
       'prcitshp', 'prcitflg', 'peinusyr', 'selfproxy', 'lfsr94', 'absent94',
       'uhourse', 'reason94', 'hourslw', 'laydur', 'dwrsn', 'why3594',
       'prunedur', 'untype', 'ftpt94', 'class94', 'agri', 'eligible', 'otc',
       'ernpdh2', 'paidhre', 'earnhre', 'earnwke', 'unionmme', 'unioncov',
       'schenr', 'studftpt', 'schlvl', 'earnwt', 'weight', 'chldpres',
       'ownchild', 'I25d', 'I25c', 'I25a', 'I25b', 'qstnum', 'occurnum', 'ged',
       'gedhigr', 'yrcoll', 'grprof', 'gr6cor', 'ms123', 'cmpwgt', 'ind02',
       'occ00', 'occ002', 'vet1', 'vet2', 'vet3', 'vet4', 'linedad', 'linemom',
       'recnum', 'year', 'ym_file', 'ym', 'ch02', 'ch35', 'ch613', 'ch1417',
       'ch05', 'ihigrdc', 'docc00', 'dind02'],
      dtype='str')

In [14]:
smaller_df = df[['hhid', 'state', 'county', 'class94', 'earnhre', 'age', 'sex', 'grade92', 'unioncov', 'uhourse', 'weight']]
smaller_df.head()

,hhid,state,county,class94,earnhre,age,sex,grade92,unioncov,uhourse,weight
0,2600310997690,63,0,4.0,2100.0,41,1,39,2.0,40.0,2846.6161
1,2600310997690,63,0,5.0,2100.0,40,2,44,2.0,37.0,3118.6074
2,7087707096191,63,0,4.0,NaN,40,1,44,2.0,40.0,3719.7807
3,7087707096191,63,0,NaN,NaN,38,2,44,NaN,NaN,2804.8039
4,41110310970391,63,73,6.0,NaN,68,1,43,NaN,30.0,3554.8098

In [27]:
#Illinois = state == 33
illinois_df = smaller_df[smaller_df['state'] == 33]
illinois_df

,hhid,state,county,class94,earnhre,age,sex,grade92,unioncov,uhourse,weight
7642,3906691195777,33,0,4.0,NaN,29,1,39,NaN,NaN,4359.0138
7643,18351370993090,33,0,5.0,NaN,23,2,39,NaN,40.0,3775.5995
7644,31691370940990,33,0,5.0,NaN,26,1,43,2.0,40.0,4153.6278
7645,33341370924585,33,0,4.0,3500.0,47,2,44,2.0,-4.0,2972.9270
7646,33341370924585,33,0,6.0,NaN,47,1,42,NaN,40.0,2833.8796
...,...,...,...,...,...,...,...,...,...,...,...
299348,967193249700939,33,113,2.0,NaN,41,2,46,2.0,40.0,2771.0185
299349,967193249700939,33,113,1.0,1075.0,42,1,40,NaN,60.0,2837.2760
299350,972047864169070,33,113,NaN,NaN,70,2,37,NaN,NaN,2640.0773
299351,976047815129860,33,115,7.0,NaN,54,2,40,NaN,17.0,2723.0936
299352,976047815129860,33,115,7.0,NaN,42,1,40,NaN,60.0,2784.1148

In [23]:
illinois_df['earnhre'].isna().sum()

np.int64(6604)

In [24]:
illinois_df['unioncov'].isna().sum()

np.int64(5134)

In [26]:
illinois_df['uhourse'].isna().sum()

np.int64(3642)

Government jobs (federal, state, local) are codes 1, 2, and 3.
Private, for profit jobs are 4
Private, non-profit jobs are 5

Should we count nonprofit as private?

In [35]:
#Creating IL public df

illinois_public_df = illinois_df[illinois_df['class94'].isin([1, 2, 3])]
illinois_public_df['earnhre'].mean()

np.float64(1674.8691860465117)

In [33]:
#Creating IL private df
illinois_private_df = illinois_df[illinois_df['class94'].isin([4, 5])]
illinois_private_df['earnhre'].mean()

np.float64(1429.962187958884)

In [38]:
#Creating other states public df
other_states_df = smaller_df[smaller_df['state'] != 33]
public_other_states_df = other_states_df[other_states_df['class94'].isin([1, 2, 3])]
public_other_states_df['earnhre'].mean()

np.float64(1770.5928134894339)

Creating a new dataframe to display all of the summary statistics we want for 2008