In [7]:
import pandas as pd
import numpy as np

df = pd.read_csv("/Users/rebeccasonn-lees/Downloads/PDI/pdi_pensions/data/csv/morg08.csv")
df.head()
df.columns

Index(['hhid', 'intmonth', 'hurespli', 'hrhtype', 'minsamp', 'hrlonglk',
       'hrsample', 'hrhhid2', 'serial', 'hhnum', 'state', 'stfips', 'cbsafips',
       'county', 'centcity', 'smsastat', 'icntcity', 'smsa04', 'relref95',
       'age', 'spouse', 'sex', 'grade92', 'race', 'ethnic', 'lineno', 'famnum',
       'pfamrel', 'marital', 'prpertyp', 'penatvty', 'pemntvty', 'pefntvty',
       'prcitshp', 'prcitflg', 'peinusyr', 'selfproxy', 'lfsr94', 'absent94',
       'uhourse', 'reason94', 'hourslw', 'laydur', 'dwrsn', 'why3594',
       'prunedur', 'untype', 'ftpt94', 'class94', 'agri', 'eligible', 'otc',
       'ernpdh2', 'paidhre', 'earnhre', 'earnwke', 'unionmme', 'unioncov',
       'schenr', 'studftpt', 'schlvl', 'earnwt', 'weight', 'chldpres',
       'ownchild', 'I25d', 'I25c', 'I25a', 'I25b', 'qstnum', 'occurnum', 'ged',
       'gedhigr', 'yrcoll', 'grprof', 'gr6cor', 'ms123', 'cmpwgt', 'ind02',
       'occ00', 'occ002', 'vet1', 'vet2', 'vet3', 'vet4', 'linedad', 'linemom',
       'recnum', 'year', 'ym_file', 'ym', 'ch02', 'ch35', 'ch613', 'ch1417',
       'ch05', 'ihigrdc', 'docc00', 'dind02'],
      dtype='str')

In [8]:
smaller_df = df[['hhid', 'state', 'county', 'class94', 'weight']]
smaller_df.head()

             hhid  state  county  class94     weight
0   2600310997690     63       0      4.0  2846.6161
1   2600310997690     63       0      5.0  3118.6074
2   7087707096191     63       0      4.0  3719.7807
3   7087707096191     63       0      NaN  2804.8039
4  41110310970391     63      73      6.0  3554.8098

In [11]:
#Illinois = state == 33
illinois_df = smaller_df[smaller_df['state'] == 33]
illinois_df.head()

                hhid  state  county  class94     weight
7642   3906691195777     33       0      4.0  4359.0138
7643  18351370993090     33       0      5.0  3775.5995
7644  31691370940990     33       0      5.0  4153.6278
7645  33341370924585     33       0      4.0  2972.9270
7646  33341370924585     33       0      6.0  2833.8796