In [2]:
import pandas as pd
import numpy as np

In [3]:
analytic = pd.read_csv("/Users/vedikabaradwaj/Documents/analytic_sample_0809_recruitment.csv")
analytic.head()

,hhid,intmonth,hurespli_t,hrhtype_t,minsamp_x,hrlonglk_t,hrsample_t,hrhhid2_t,serial_t,hhnum,...,pair_type,state_t,illinois,pair,joined_state_local,from_federal,from_private,from_nlf_unemp,same_state_t1,analytic_sample
0,34371770972784,1,1.0,6,4,2,8300,83001,1,1,...,MIS4_to_MIS8,illinois,1,2008-2009,0,0,0,1,1,recruitment
1,79051770926697,1,1.0,7,4,2,8300,83001,1,1,...,MIS4_to_MIS8,illinois,1,2008-2009,0,0,0,1,1,recruitment
2,79051770926697,1,1.0,7,4,2,8300,83001,1,1,...,MIS4_to_MIS8,illinois,1,2008-2009,0,0,1,0,1,recruitment
3,92311770998383,1,1.0,7,4,2,8300,83001,1,1,...,MIS4_to_MIS8,illinois,1,2008-2009,0,0,0,1,1,recruitment
4,177193558700598,1,1.0,7,4,2,8300,83001,1,1,...,MIS4_to_MIS8,illinois,1,2008-2009,0,0,0,1,1,recruitment

In [30]:
analytic2 = pd.read_csv("/Users/vedikabaradwaj/Documents/analytic_sample_0809_retention.csv")
analytic2.head()

,hhid,intmonth,hurespli_t,hrhtype_t,minsamp_x,hrlonglk_t,hrsample_t,hrhhid2_t,serial_t,hhnum,...,illinois,pair,stayed_state_local,exited_state_local,moved_to_federal,moved_to_private,moved_to_nlf_unemp,switched_class94,same_state_t1,analytic_sample
0,450778093617847,1,1.0,1,4,2,8300,83001,1,1,...,1,2008-2009,1,0,0,0,0,0,1,retention
1,778430773420971,1,1.0,6,4,2,8300,83001,1,1,...,1,2008-2009,1,0,0,0,0,0,1,retention
2,968007952179410,1,1.0,4,4,2,8300,83001,1,1,...,1,2008-2009,1,0,0,0,0,1,1,retention
3,10975091417959,1,1.0,7,4,2,8300,83001,1,1,...,1,2008-2009,1,0,0,0,0,0,1,retention
4,33341770924575,1,1.0,6,4,2,8300,83001,1,1,...,1,2008-2009,0,1,0,1,0,1,1,retention

In [7]:
analytic_df2 = analytic.copy()

In [13]:
analytic_df2["weighted_earnings_t"] = analytic_df2["earnwke_t"] * analytic_df2["earnwt_t"]

In [16]:
analytic_df2["weighted_earnings_t"].describe()

count    9.383000e+03
mean     1.015609e+07
std      7.810482e+06
min      0.000000e+00
25%      4.865842e+06
50%      8.121025e+06
75%      1.299560e+07
max      6.069377e+07
Name: weighted_earnings_t, dtype: float64

In [18]:
analytic_df2["earnwt_t"].describe()

count    18302.000000
mean     12368.533296
std       2101.580598
min          0.000000
25%      11040.886700
50%      11979.925700
75%      13328.717200
max      54439.994600
Name: earnwt_t, dtype: float64

In [28]:
analytic_df_under35 = analytic_df2[analytic_df2["age_t"]<= 35]
analytic_df_under35 = analytic_df_under35[analytic_df_under35["age_t"] >= 16]

In [29]:
analytic_df_under35["age_t"].describe()

count    4843.000000
mean       25.601487
std         6.071597
min        16.000000
25%        20.000000
50%        26.000000
75%        31.000000
max        35.000000
Name: age_t, dtype: float64